name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t custom-adspower-env .

    - name: Save Docker image to tar file
      run: |
            docker save -o custom-adspower-env.tar custom-adspower-env

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: custom-adspower-env
        path: custom-adspower-env.tar
